### ISSUE TITLE
No response when using the "Ask Open Canvas" feature for editing.

### ISSUE THREAD

**Issue by sonnt-dna** [langchain-ai/open-canvas#106]
When using the "Ask Open Canvas" feature to request changes in the document editor, there is no response returned by the system. The issue persists even after attempting to make further changes via the chat interface.

**Steps to Reproduce:**
1. Open the document editing interface.
2. Request a change to a highlighted section using the "Ask Open Canvas" button.
3. Observe that no response is given by the system.
4. Attempt to make additional requests using the chat input field.
5. Notice that still no response is provided.

**Expected Behavior:**
The system should provide a response to the user's request, either allowing edits or providing guidance, similar to the cloud version.

**Observed Behavior:**
- No response is given when using "Ask Open Canvas".
- No response is provided even after repeated requests via the chat.

**Environment:**
- Version: Local server (localhost:3000)
- Document Title: "Whispers of the Sea"
- Specific section attempted for edit: The final paragraph, highlighted in blue.

**Screenshots:**
(Attach the provided screenshot showing the issue)

**Additional Information:**
This issue does not occur in the cloud version, where the requested edits are processed successfully.

**Severity:**
High - Blocks editing functionality, disrupting user workflow.

**Potential Cause:**
- The issue may be related to differences in the backend processing logic between the local and cloud environments.

**Suggested Label:**
- Bug
- Editing Functionality
![image](https://github.com/user-attachments/assets/b9bae98b-f816-45ec-9838-81f7844c548b)

**Comment by sonnt-dna** [comment]
This detail for errors: 
langgraph-api-1       | FAILED TO GENERATE TOOL CALL {
langgraph-api-1       |   styleRules: [
langgraph-api-1       |     'Use clear and concise language to explain complex concepts, ensuring accessibility for a broad audience.',
langgraph-api-1       |     'Structure written content with clear headings and subheadings to enhance readability and organization.',
langgraph-api-1       |     'Incorporate historical context and practical applications to provide depth and relevance to the topic being discussed.'
langgraph-api-1       |   ],
langgraph-api-1       |   content: [
langgraph-api-1       |     'The user is interested in writing articles, particularly on technical subjects like Design of Experiments (DoE).',
langgraph-api-1       |     "The user values detailed and thorough explanations, as indicated by their request to 'chi tiết hoá' (detail) the article.",
langgraph-api-1       |     'The user is open to further adjustments and additional information regarding the content they are working on.'
langgraph-api-1       |   ]
langgraph-api-1       | }
langgraph-api-1       | Error: Reflection tool call failed.
langgraph-api-1       |     at RunnableLambda.reflect (/Volumes/DATA/open-canvas-main/src/agent/reflection/index.ts:80:11)
langgraph-api-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
langgraph-api-1       |     at async /Volumes/DATA/open-canvas-main/node_modules/@langchain/core/dist/runnables/base.cjs:1531:34 {
langgraph-api-1       |   pregelTaskId: '15c3f8ee-7a7e-5ec3-96c7-3dddfb405f73'
langgraph-api-1       | }

**Comment by bracesproul** [comment]
@sonnt-dna that's the reflection graph, which is not blocking the open canvas graph from executing. I also made a change sometime next week which should mitigate those errors in the reflection graph. I'm going to close this issue now, please ping me if you encounter another error.
