### ISSUE TITLE
How to run OpenCanvas locally on Linux?

### ISSUE THREAD

**Issue by PieBru** [langchain-ai/open-canvas#109]
Hi, great project!
If I understood correctly, OpenCanvas needs LangGraph, which as of now is available for local installation only on MacOS.
I feel blind, but wasn't able to find an easy way to couple a local OpenCanvas to an LangGraph cloud API.
Please point me in the right direction.
Thank you.
Piero

**Comment by bracesproul** [comment]
We're working on adding better support for running LangGraph Cloud apps on Windows/Linux in the coming weeks! I'll post an update in this repo & update the Readme once that's ready

You can also deploy Open Canvas on LangGraph Cloud which only requires a LangSmith Plus subscription.

**Comment by PieBru** [comment]
Great! Being a single dev, I will wait for the update. Thanks
