### ISSUE TITLE
cuando vi que pedis lo de Studio que solo se puede descargar en mac ya tenia media instalacion echa jaja

### ISSUE THREAD

**Issue by sontoriyama** [langchain-ai/open-canvas#111]
en windows sacareis un docker aunque sea¿? cuando creeis que podré usarlo en windows?  gracias, hacia dias que pensaba que habia de haver un open source del canvas de gpt pero solo encontré un proyecto de hace un año con este nombre y pedia dependencias peligrosas que no me atreví a instalar jeje

**Comment by bracesproul** [comment]
hey, so we are planning on adding better support for running on windows/linux, however it won't be ready for a couple weeks.

In the meantime you can still deploy on LangGraph Cloud, it only requires a LangSmith Plus account
