### ISSUE TITLE
yarn fail

### ISSUE THREAD

**Issue by sontoriyama** [langchain-ai/open-canvas#112]
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "codemirror@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react@^17.0.0 || ^16.3.0 || ^15.5.4".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react-dom@^17.0.0 || ^16.3.0 || ^15.5.4".
warning "react-json-view > flux@4.0.4" has incorrect peer dependency "react@^15.0.2 || ^16.0.0 || ^17.0.0".
info There appears to be trouble with your network connection. Retrying...
[4/4] Building fresh packages...
Done in 72.59s.
PS C:\eines\copia-canvas-gpt\open-canvas>

**Comment by bracesproul** [comment]
```
info There appears to be trouble with your network connection. Retrying...
```
your network issue, not a bug.
