### ISSUE TITLE
Is there any way to run this on windows?

### ISSUE THREAD

**Issue by inweb-pro** [langchain-ai/open-canvas#114]

**Comment by bracesproul** [comment]
We're working on adding better support for running LangGraph Cloud apps on Windows/Linux in the coming weeks! I'll post an update in this repo & update the Readme once that's ready

**Comment by Julsgaard** [comment]
@lanesky 
Do you know why the LangSmith API key is needed if LangGraph is open source and can be run locally?

I'm working on a project where privacy is crucial, so we need to run everything locally, including the LLM (hopefully this is possible with open-canvas). Any insights would be greatly appreciated!

**Comment by IsraelShok** [comment]
@Julsgaard I also trying to find a way to run this locally to save privacy. 
If you find a way, please share.
Thanks!

**Comment by MrunalKashid02** [comment]
@lanesky could you please help me to set open canvas locally

**Comment by inweb-pro** [comment]
Look better Mistral AI for free

**Comment by IsraelShok** [comment]
@inweb-pro It's an open source?
