### ISSUE TITLE
Implement thumbs up/down in chat

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#122]
We should add support for giving feedback when runs complete. Implement it the same way we implement langsmith URLs atm (custom UI component that is rendered when a tool is present in a message)

Spec:
Add a `feedback_tool_ui` tool when the streaming completes to the last `AIMessage` that is displayed in the chat. This tool UI should render a thumbs up/down. When clicked, it should append feedback to the run in langsmith (see [this doc for a how-to](https://docs.smith.langchain.com/how_to_guides/human_feedback/attach_user_feedback)). The feedback key should be named `feedback` and it's score should either be `0` (thumbs down) or `1` (thumbs up).

Only allow users to give feedback once per run. If a user clicks on the thumbs up/down, it should be removed and replaced with a message along the lines of `Thanks, your feedback has been recorded` (feel free to improve that message!)

**Comment by ahmad2b** [comment]
Hi @bracesproul! I wanted to share my thoughts on implementing the feedback feature.
When looking at the spec, I initially tried implementing it like the LangSmith share URLs (showing up as tools), but I feel this might not be the most natural place for users to find and use the feedback buttons.

While exploring alternatives, I noticed we could use the ActionBarPrimitive to create a feedback component for assistant messages. This would:
- Put the feedback buttons below assistant messages
- Set and pass the runId from useGraph to this component
- Let us easily handle the feedback submission using LangSmith client

What do you think about this approach? I want to ensure I'm heading in the right direction before proceeding. Would love to hear your thoughts or if you had something different in mind!

**Comment by bracesproul** [comment]
Hey @ahmad2b I like how that sounds! Would you like me to assign this issue to you?

**Comment by ahmad2b** [comment]
Great, I'd be glad to take this on!

**Comment by Sarfaraz021** [comment]
this is something can we implement now in langgraph?? if yes please share documentation @ahmad2b @bracesproul
