### ISSUE TITLE
Add Gemini 1.5 Flash to model options

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#141]
This is only in the `staging` branch atm, so you'll need to checkout that branch first. Update the fields inside `constants.ts` to include Gemini 1.5 Flash. Install `@langchain/google-vertexai`, then test. It should be as simple as that!

**Comment by mjunaidca** [comment]
Hi @bracesproul!

This PR adds Gemini 1.5 Flash to the model options in the staging branch as outlined in issue #141, with dependencies and authentication configured. Testing confirmed the model appears in the options, API calls authenticate successfully, and no errors were encountered.

Kindly review when you have a chance, and let me know if there’s anything else I can adjust. Thanks!
