### ISSUE TITLE
Background job for generating titles of chats

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#152]
The logic for getting the title of a chat history is to just take the input message and make that the title (truncated). This is _not_ ideal. My idea for the new flow should be as follows:

1. Setup a subgraph (this way it can run in the background and not be blocking) the same way we setup & call the `reflection` graph (as a node inside the main graph which calls the subgraph via the LangGraph SDK). Add a new directory inside `./src/agent`, and add this graph to the `langgraph.json` file.
2. This subgraph should only execute at the end of a run, if it was the first run in a thread (1 user message)
3. It should take the user message, and the generated artifact, and response to message (or just response if no artifact was generated) and prompt the LLM to generate an extremely short title for this thread. Ideally, we never need to truncate these titles.
4. Once generated, it should then call the LangGraph SDK to update the metadata on the thread with a new field `thread_title`.
5. Update the client side code which gets the title for the thread to first look in the thread metadata for this field, and if it doesn't exist, fallback to the current logic.
6. We should use `gpt-4o-mini` to generate this title. Do not use the configured model to do this.

**Comment by ahmad2b** [comment]
Hey @bracesproul, Thank you for the detailed spec!

I've submitted a PR (#165) that implements the background jobs for generating chat titles as you suggested. It runs in the background, updates the thread `metadata` with a new `thread_title` field, and uses `gpt-4o-mini` to create concise titles.

Please check it out and let me know what you think!
