### ISSUE TITLE
how can adding GEMINI api key

### ISSUE THREAD

**Issue by thx404** [langchain-ai/open-canvas#160]
I need plis, I don't know how to put it on

**Comment by ahmad2b** [comment]
You can use Gemini by switching to the staging branch. Make sure you've added your Gemini API key to the .env file with the `GOOGLE_API_KEY` variable.

**Comment by bracesproul** [comment]
@thx404 What @ahmad2b said is true, however I've discovered an issue with streaming tool calls in the `@langchain/google-genai` package, so I've disabled the Gemini integration for now. I'm working on a fix in the LangChain.js repo though, and once that's done I'll reenable it in staging.
