### ISSUE TITLE
Open Canvas on LangGraph Cloud direction

### ISSUE THREAD

**Issue by peanutdev** [langchain-ai/open-canvas#196]
I would appreciate it if anyone can point me in the right direction for getting this up and running in LangGraph Cloud. I have a LangSmith Plus subscription. I am new at this.

It appears https://opencanvas.langchain.com/ is running in Vercel, so I did the same. But notices localhost:3000.

I added `NEXT_PUBLIC_API_URL` to Vercel and the API URL from LangGraph Platform when I deployed my private repo, the same which is deployed at Vercel. Then I see localhost:3000 is replaced with the API URL but that is http status 403.

Thank you

**Comment by bracesproul** [comment]
@peanutdev to run this in production, fork this repo, deploy on langgraph cloud setting these environment variables: 
- `ANTHROPIC_API_KEY`
- `OPENAI_API_KEY`

Then, deploy to vercel and set these environment variables:
- `NEXT_PUBLIC_API_URL` (this should be the production domain + `/api` e.g `https://opencanvas.langchain.com/api`
- `LANGGRAPH_API_URL` the api url from your LangGraph Cloud deployment
- `LANGCHAIN_API_KEY` required for authing to your LangGraph Cloud deployment
- `NEXT_PUBLIC_SUPABASE_ANON_KEY` - for auth
- `NEXT_PUBLIC_SUPABASE_URL` - for auth

**Comment by bracesproul** [comment]
@peanutdev  This video walks through how to setup and run the project locally: https://www.youtube.com/watch?v=sBzcQYPMekc

I also added this section with common errors and solutions: https://github.com/langchain-ai/open-canvas?tab=readme-ov-file#troubleshooting
