### ISSUE TITLE
Open Canvas on Langgraph

### ISSUE THREAD

**Issue by akademi59222** [langchain-ai/open-canvas#199]
I would really appreciate it if anyone help me run this project on local.

I run open-canvas on my local windows but some errors are happening.

These api request were failed.

**POST /api/assistants/search 500**
 Error in proxy
TypeError: fetch failed

**POST /api/threads 500**
Error in proxy
TypeError: fetch failed

**POST /api/assistants 500**
Error in proxy
TypeError: fetch failed

I think the reason is lagngraph sever is not running on localhost:54367.

Please let me know how I can run open-canvas on local windows or mac os  and how to deploy langgraph to cloud and deploy open-canvas?

**Comment by IsraelShok** [comment]
There is a previous comment about running it locally with docker-compose or in separate containers (redis, postgres, and the server).

**Comment by bracesproul** [comment]
This video walks through how to setup and run the project locally: https://www.youtube.com/watch?v=sBzcQYPMekc

I also added this section with common errors and solutions: https://github.com/langchain-ai/open-canvas?tab=readme-ov-file#troubleshooting
