### ISSUE TITLE
Running the project on Ubuntu,

### ISSUE THREAD

**Issue by smtabatabaie** [langchain-ai/open-canvas#201]
Hi guys,
I wanted to ask if it is possible to run the project on ubuntu without Langgraph studio (mac). And also ask to what are LANGGRAPH_API_URL and  LANGCHAIN_API_KEY in the .env file and where can i find them? I only have an API Key which i created in langsmith panel.
Thanks

**Comment by DevHusnainAi** [comment]
@smtabatabaie If you want to run i locally in docker than you can use the same key in both

**Comment by bracesproul** [comment]
This video walks through how to run the project locally (ubuntu supported!): https://www.youtube.com/watch?v=sBzcQYPMekc
