### ISSUE TITLE
How to use src/agent/open-canvas as the server side?

### ISSUE THREAD

**Issue by honestAnt** [langchain-ai/open-canvas#204]
What is the configuration in this directory in the project? Can it be used as an independent back-end service to provide functions similar to langgraph studio [memory-agent-js] ?

**Comment by bracesproul** [comment]
Yes it can be! The `langgraph.json` file is the configuration file which langgraph studio/cloud uses to run the project

**Comment by honestAnt** [comment]
OK, thanks for letting me know
