### ISSUE TITLE
how to disable trace or log upload to langchain platform

### ISSUE THREAD

**Issue by xibudadao** [langchain-ai/open-canvas#211]
For example, this information will be automatically uploaded to the platform, and I want to prohibit uploading because some of it may involve private data.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implemented a data privacy check in the API routes for storing and retrieving data, and updated the useStore hook to handle this new check. This prevents automatic uploading of potentially private data.

You can review changes in this commit: https://github.com/mnmnk43434/langchain-ai-open-canvas-211/commit/1f4ca2aba23898bcc4299deb872f962012f57ad2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hinthornw** [comment]
You can set LANGSMITH_TRACING=false

**Comment by bracesproul** [comment]
Will's comment is correct! Just add `LANGSMITH_TRACING=false` as an environment variable
