### ISSUE TITLE
Documentation, Dependencies, Endless Blockades, Nightmares and more, wrapped in a cultural miasma. 

### ISSUE THREAD

**Issue by sid-newby** [langchain-ai/open-canvas#213]
# Open Canvas: A Missed Opportunity. 
I've just spent hours attempting to install and run Open Canvas. 
This experience has highlighted systemic issues that i've experienced over the last couple of years with really every release i've tried with the LangChain brand name on it. I've been meaning to have a heart to heart with Langchain, et.al. Thanks in advance for suffering through this. it comes from a place of love. We want to love you but there are some things that need to be addressed. 

## The Setup Experience
1 Clone repo, yarn install - hit first wall of dependency warnings including:
	* React version conflicts and vulnerabilities scrolling for pages
	* CodeMirror peer dependencies missing
	* IBM Watson dependencies no one asked for or discussed
2  
```brainfuck
warning "react-json-view@1.21.3" has incorrect peer dependency "react@^17.0.0 || ^16.3.0 || ^15.5.4"
3 warning "@uiw/react-codemirror@4.23.5" has unmet peer dependency "codemirror@>=6.0.0" 
```

4 Supabase setup - surprise requirement!
	* Only mentioned in .env
	* No docs on what tables or schema needed
	* No local Postgres alternative
	* Get a random "thanks for signing up" email that could be from anywhere
	* Used in authentication flow, only after realizing no documentation was provided for google/git oAuth flows. 
	* Not a single mention in the signup email that this is in response to the open-canvas signup 
	* Ultra ambiguous as many users just signed up for supabase to satisfy this non-documented 'feature'. it looks like it's an email confirmation from supabase re: new signup/db etc. No documentation for this event. 
5 Authentication
	* Google OAuth not documented
	* GitHub OAuth not documented
	* Email signup works but see 4. 
6 LangGraph Integration
	* LangGraph hits 150% CPU with 10 allocated cores on 2024 m1 while IDLE
	* Model config missing with zero guidance:
7 typescript
	* on throw new Error("Model name is missing in config.");
	* README references non-existent function `getModelNameAndProviderFromConfig`
	* Reflector agent needs undocumented `open_canvas_assistant_id`
	* - the only place in the project the message - `Model name is missing in config. -`  is thrown is in `src/agent/utils.ts`
	* When it's thrown, there is no indication on how to edit it, what file it's in, what system is failing... is it supabase? your hosting provider? langgraph studio? the ui of the react app? Searching the codebase, you finally stumble on the Readme, which indicates models are configured in a function that does not exist. 💀

## The Real Issues
**1** **At Langchain, Documentation is an Afterthought, user experience is akin to sabotage**
	* Essential setup steps missing
	* Configuration requirements discovered through errors
	* No troubleshooting guide
	* Existing docs reference non-existent code
	
**2** **Quality Control and maintenance of branded source code is non-existent**
	* Langgraph studio resource management is broken
	* Dependency conflicts shipped to main
	* Basic configuration missing from default install
	* Error messages provide zero actionable information
	
**3** **User Experience is Hostile**
	* 90% of users likely fail first install
	* Critical requirements hidden until failure
	* No clear path to resolution
	* Basic features require undocumented external services

## The Broader Problem
LangChain has incredible technology that should be part of every LLM project. Instead:
* You're weaving language into every release as if LangSmith were a hard requirement 
* Investments of $10m last year and $35m this year when langsmith is your only real revenue generator and let's face it.. it's `passable`
* Logfire free tier starts at 1 million calls per month, while langsmith offers 5k. You can eat up 5k calls in an afternoon in dev with a multi-agent framework. 
* Documentation is consistently inadequate, outdated or just wrong across all projects, tutorials, quick starts. Not exaggerating. 
* Basic setup issues block most users from even starting. 
* `Cult of Langchain` Cultural arrogance is preventing recognition of these issues

## Wake up. 
**1** **You're blowing it. You need to get back to basics and take care of your first timers.**
	* Establish minimum standards of launch and cadenced maintenance routines for all project owners. If it's got the langchain brand on it, it needs to be fucking polished. You cant allow your product to be represented in this way. Brace, if you're done fucking with this thing, archive it. Dont waste your customer's time with an unusable, unmaintained, undocumented waste of 4 hours. Consider you've potentially damaged the brand 100,000 times with this library. All of the videos, marketing, conventions, meets whatever lead me, a burned prospect who decided to give it another try to this project, just to be met with a literal deluge of confusion, dead ends, incompatibilities and senseless beatings. Ok, another broken repo on GitHub, I get it... but this one says 'LANGCHAIN' on it.  Dig? 
	* Document ALL configuration requirements
	* Fix resource management, or note that it's a thing and will be improved. (likely on retries for code that doesnt work and doesnt timeout due to issues mentioned in this post or otherwise)
	* Add clear error messages with resolution steps. 
	* Provide local development alternatives 
**2** **Who's driving this thing? **
	* Hire a full-time documentation team, or better yet, an agentic library and give it to your users. 
	* Assign ownership of public-facing assets. Use dependabots. 
	* Implement documentation quality gates. Assign responsible owners. Maybe you're busy, but if its got the brand name on it, its bigger than you. This becomes an organizational effort the moment you commit public with the company name attached. 
	* Implement a Regular documentation audit cadence. If you cant prioritize fixes, prioritize a line of text at the head of your README.md 

This isn't just about Open Canvas - it's about a pattern. Langchain has raised significant funding, 10m 2023 and 35m in 2025? The guys at Sequoia may dress funny, but they're not chumps. You guys have built amazing tech, but are failing at the basics of software distribution at the critical stage of new user onboarding/orientation. Your technology should be powering the future of AI development, but instead: I challenge you to present a new prospective developer with any published walkthrough, tutorial, signup, quickstart or repo.. and watch them. Just take a fucking afternoon and check in on the new user experience. Its brutal. 
* Users can't get past basic setup
* Documentation is consistently inadequate
* Error messages are useless
* Basic configuration is missing

⠀Someone needs to put on their C-Suite pants and go to fucking work. Langchain is wasting a golden opportunity we'd all kill for. Be ashamed.
- *For reference, full dependency warning list:*
```pipeline-poison
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning "@blocknote/mantine > @blocknote/react > @tiptap/react@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning "@blocknote/mantine > @blocknote/react > @tiptap/react > @tiptap/extension-bubble-menu@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning "@blocknote/mantine > @blocknote/react > @tiptap/react > @tiptap/extension-floating-menu@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning " > @langchain/community@0.3.9" has unmet peer dependency "@ibm-cloud/watsonx-ai@*".
warning " > @langchain/community@0.3.9" has unmet peer dependency "ibm-cloud-sdk-core@*".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/autocomplete@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/language@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/state@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/view@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/common@^1.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/highlight@^1.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/lr@^1.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "codemirror@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react@^17.0.0 || ^16.3.0 || ^15.5.4".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react-dom@^17.0.0 || ^16.3.0 || ^15.5.4".
warning "react-json-view > flux@4.0.4" has incorrect peer dependency "react@^15.0.2 || ^16.0.0 || ^17.0.0".
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/Users/sidnewby/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning "@blocknote/mantine > @blocknote/react > @tiptap/react@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning "@blocknote/mantine > @blocknote/react > @tiptap/react > @tiptap/extension-bubble-menu@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning "@blocknote/mantine > @blocknote/react > @tiptap/react > @tiptap/extension-floating-menu@2.8.0" has unmet peer dependency "@tiptap/pm@^2.7.0".
warning " > @langchain/community@0.3.9" has unmet peer dependency "@ibm-cloud/watsonx-ai@*".
warning " > @langchain/community@0.3.9" has unmet peer dependency "ibm-cloud-sdk-core@*".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/autocomplete@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/language@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/state@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@codemirror/view@^6.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/common@^1.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/highlight@^1.0.0".
warning " > @replit/codemirror-lang-csharp@6.2.0" has unmet peer dependency "@lezer/lr@^1.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > @uiw/react-codemirror@4.23.5" has unmet peer dependency "codemirror@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.23.5" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react@^17.0.0 || ^16.3.0 || ^15.5.4".
warning " > react-json-view@1.21.3" has incorrect peer dependency "react-dom@^17.0.0 || ^16.3.0 || ^15.5.4".
warning "react-json-view > flux@4.0.4" has incorrect peer dependency "react@^15.0.2 || ^16.0.0 || ^17.0.0".
```

# Fix this. You're better than this. 
I want to love you guys but its gonna require attention from the top, some work ethic, and the realization that you're a big company now at a critical time in humanity's history and you've got a direct opportunity to be at the heart of it. I cant think of an LLM based development asset i've been involved in for the past several years that wouldn't benefit from Langchain, et.al being part of the stack. Your customer is a developer. if they released this with the company name and even worse, left it out there to rot like this project has, theyd never live it down. Its plain negligence, my dudes. You've got to realize the damage it does to the brand.  

Be an agent for change or become irrelevant. Langchain's competitors are beating at the castle gates, dying to get a piece of them. Even though they've got some of the most kickass technology in the entire game. It doesn't make a shit if you cant get it into the user's hands. 

Theres 100x the number of new `developers` today vs5 years ago. The company must adopt a prospect conversion mindset and a standard for releases considering the average developer. Make them 'office famous' and they'll pay you forever. Little guys go to big companies sometimes. Sometimes they bring you with them. 

We'll be watching. I hope we can work together again sometime.

**Comment by bracesproul** [comment]
@sid-newby First, thank you for taking the time to try it out locally, and writing this detailed issue with the issues/problems you faced. To address some of your concerns, I've released an updated video walkthrough showing how to setup and run the project locally ([here](https://www.youtube.com/watch?v=sBzcQYPMekc)). This should address your concerns with problems setting up the project locally.

Additionally, I updated the readme to include [a new troubleshooting section](https://github.com/langchain-ai/open-canvas?tab=readme-ov-file#troubleshooting) with common errors and explanations.

Lastly, the custom LLM section has been updated to include the proper instructions on how to add support for new models.

Thank you for taking the time to write all of this down, and we're working hard to improve the developer experience around this, and all of our projects!
