### ISSUE TITLE
how to deploy LangGraph 

### ISSUE THREAD

**Issue by SericWong** [langchain-ai/open-canvas#44]
How to deploy LangGraph locally, can you provide detailed instructions? I have downloaded LangGraph Studio and want to deploy it locally. I’m not sure what to do next.

**Comment by bracesproul** [comment]
If you have LangGraph studio downloaded locally, you can follow these instructions to get up and running: https://github.com/langchain-ai/langgraph-studio/blob/main/README.md

Ensure you have docker running. The `langgraph.json` config file is in the root of this repository.

Then once the app is running, in the bottom left of the screen you'll see a localhost URL. Copy that, and replace the current localhost URL of `LANGGRAPH_API_URL` in `src/constants.ts`. 

Also ensure you have all the necessary environment variables set.
