### ISSUE TITLE
deploy need 2core and 2g memory?

### ISSUE THREAD

**Issue by menhuan** [langchain-ai/open-canvas#47]

**Comment by bracesproul** [comment]
Hey @menhuan could you provide more context? Not really sure what you're asking about here.

**Comment by menhuan** [comment]
I want to deploy Open-Canvas on the cloud by myself. After deploying, I was prompted that something was missing, as shown in the image. Additionally, my machine has 2 cores and 2GB of RAM, and it seems to run quite slowly. 
how slow ..
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/9333ebb5-01c1-4063-b350-29129ba9b6d8">

**Comment by menhuan** [comment]
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/5b5a038b-c8e3-4045-b0e7-f9c336a3de03">

**Comment by bracesproul** [comment]
@menhuan the recommended way to deploy the LangGraph agent(s) is via LangGraph Studio on Mac, or by deploying on LangGraph Cloud which requires a LangSmith Plus account.

We're activity working on making this easier to deploy locally on Windows/Linux but it won't be ready for a couple weeks.

**Comment by zzggbond2mm** [comment]
i have upgrade plus  how to deploy on LangGraph Cloud ？ im confusing
