### ISSUE TITLE
Make markdown renderer extend all the way to the bottom

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#55]
atm there is some padding between the bottom/right side of the screen and the markdown editor. Update it to extend all the way to the bottom & left sides of the screen and remove the border on the bottom/left sides.

**Comment by ahmad2b** [comment]
I have created a pull request (#67 ) that addresses this issue by extending the markdown renderer to the bottom and left sides. Please review it when you have a chance.
