### ISSUE TITLE
Make model customizable

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#63]
Default model should be anthropic (will require updates, atm default is openai)
If user wants a diff model, require api key

**Comment by ahmad2b** [comment]
I have created a pull request #107  that addresses this issue—changed the default model to `gpt-4o-mini`, with configurable model selection and proper thread and model state management. Please review it when you have a chance.

![image](https://github.com/user-attachments/assets/e561d298-ad4c-4db1-a4c8-41ddb568443d)
