### ISSUE TITLE
Update runs to only ever use a single artifact

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#73]
At the moment, a single run can create as many artifacts as the user requests. We should update so it only ever generates a single artifact.

If we ship this before implementing thread history we don't need to worry about backwards compatibility around dealing with multiple artifacts.

**Comment by sid-newby** [comment]
We should update so it only ever generates a single artifact [at a time]. 
For artifact saving, consider git.  Good solution if rehydrating later too.

**Comment by bracesproul** [comment]
@sid-newby 
> We should update so it only ever generates a single artifact [at a time]. For artifact saving, consider git. Good solution if rehydrating later too.

I like this idea, and yeah I think I'm going to update it today to only ever have a single artifact per conversation (this will include #21 so you can go back and fourth between your edits). However I'm probably going to keep our existing artifact storage system in place (stored in thread state, uses the LangGraph checkpointer which will persist since it's hosted on LangGraph cloud) since it doesn't require any additional setup/config work on the dev end.
