### ISSUE TITLE
Replace chat history icon with a better icon

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#78]
This icon is only on the `staging` branch at the moment. Ideally we replace it with an icon which is more intuitive than:
![image](https://github.com/user-attachments/assets/62013fa8-2b67-4228-bc16-265681f78ade)

Line in codebase: https://github.com/langchain-ai/open-canvas/blob/a0bb8c50653b5340c05d8fb4445a60914655086b/src/components/ThreadHistory.tsx#L194

Idea: This double chat icon:
![image](https://github.com/user-attachments/assets/cefedfe6-9df2-48d1-a0dc-da6469a7e354)

**Comment by arvind2602** [comment]
I would Like to work on it

**Comment by Hisan-Z** [comment]
Hey, I would like to work in this

**Comment by Aryan-Bhendarkar** [comment]
Hello @bracesproul 

I am an open source enthusiast and would like to contribute to this repository by resolving this issue. Please assign  this issue for Hacktoberfest 2024.

Thank you!

**Comment by arvind2602** [comment]
I have finished it and submitted a pull request.
