### ISSUE TITLE
500 Internal Server Errors on Multiple API Endpoints and Thread ID Retrieval Error

### ISSUE THREAD

**Issue by sonnt-dna** [langchain-ai/open-canvas#84]
![image](https://github.com/user-attachments/assets/c0a62882-a7e6-4400-a2c6-8f5ca76e3936)
I'm experiencing repeated 500 Internal Server Errors across various API endpoints on our server, operating on port 3000. This issue seems to be affecting the server's ability to handle requests, resulting in significant disruptions to functionality. Additionally, the chat interface is presenting an error: "Thread ID not found," which indicates problems with retrieving conversation threads.

Environment:
Operating System: MacOS 14.6.1 (23G93)
Browser: Arc 

How to fix this Errors?

**Comment by bracesproul** [comment]
@sonnt-dna do you have the LangGraph server running on either [LangGraph Studio](https://studio.langchain.com/) (local) or [LangGraph Cloud](https://langchain-ai.github.io/langgraph/cloud/) (production deployment)? And if so, is the proper URL set? See [this Loom for instructions](https://www.loom.com/share/e2ce559840f14a9abf1b3d5af7686271?sid=2aa1c44f-3664-4be3-8be8-2f5b9cb1a3de)

**Comment by rajandmr** [comment]
I'm also having the same issue, Yes, I've langgraph studio running local. Getting multiple errors.

**Comment by bracesproul** [comment]
@rajandmr / @sonnt-dna what are the exact error messages you're getting? You can get them in one of two ways:
1. looking in the logs section of LangGraph Studio (this is if the requests are making it to the LangGraph server, but something is going wrong there)
2. Update the `/api/[..._path]/route.ts` file to actually log the error and not send back a generic error message & code (this is what is happening atm)

Then could you reply with those logs so I can see what the error is? Thank you

**Comment by sonnt-dna** [comment]
> @rajandmr / @sonnt-dna what are the exact error messages you're getting? You can get them in one of two ways:
> 
> 1. looking in the logs section of LangGraph Studio (this is if the requests are making it to the LangGraph server, but something is going wrong there)
> 2. Update the `/api/[..._path]/route.ts` file to actually log the error and not send back a generic error message & code (this is what is happening atm)
> 
> Then could you reply with those logs so I can see what the error is? Thank you

Thanks for your support!
I got it with your guide!
But the web is not responding when I edit content.
How Can I fix it.
![image](https://github.com/user-attachments/assets/ba26ffa9-a544-4481-8979-355290a267ff)

**Comment by sonnt-dna** [comment]
> This seems to be working for me too after pulling the latest changes. The streaming too works fine.

Thank for your comment, 
that mean, in the last version, editing result streaming is working fine?
