### ISSUE TITLE
As soon as the text gets longer than the initial space, cursor is not placed at the correct point

### ISSUE THREAD

**Issue by weidenrinde** [langchain-ai/open-canvas#87]
What to do:

Got to https://open-canvas-lc.vercel.app/
Start with an empty page, 
press 40x return and then a "x". 

What I expect:

Cursor after the "x"

What I saw:

The cursor is placed one line above.
![grafik](https://github.com/user-attachments/assets/0a55020c-2d85-40af-9996-6c1ac604fb1a)

![grafik](https://github.com/user-attachments/assets/8f646e5f-493a-4f94-9d2e-8e965558d611)

**Comment by bracesproul** [comment]
@weidenrinde is this in the markdown editor or the chat input?

**Comment by bracesproul** [comment]
This is fixed in `staging`. Will be merged into `main` tonight!
