### ISSUE TITLE
Possible to turn off auth?

### ISSUE THREAD

**Issue by msabramo** [langchain-ai/open-canvas#90]
Hi @bracesproul! Nice project!

My colleagues and I were trying to get open-canvas running locally and still haven't fully gotten it working.

I noticed that Auth was added in https://github.com/langchain-ai/open-canvas/commit/091c07149a0b86a25401be03bb7f53aae9fbe31a#diff-73d7a23e5015801b9bcc9db601d6ec9594d3eb34e5bb23154e0ae4b0c30f1a3b and now it requires Supabase, another dependency.

Is it possible to turn off auth so we don't have to have a dependency on Supabase for installs on our laptops? It seems like this might've made a project that is somewhat challenging to get up and running even more challenging to get up and running, unless you have some tips?

**Comment by bracesproul** [comment]
hey @msabramo turning off auth would require some significant code changes, and is not something I'd want committed to this repo (you'd be free to do it on a fork though!).

I'll be updating the readme later today with a new video demonstrating how to setup the project with auth enabled.

**Comment by ai-jz** [comment]
So sad to hear this. This will block a lot of users, imho

**Comment by lucacri** [comment]
I agree with @ai-jz , adding auth is out of the scope of the tool itself, and choosing one auth method over another is just arbitrary, and _will_ definitely clash with most other environments. So, as it stands, if you happen to use Supabase already in your system, then you are good. Otherwise, like me, I can't even start it :-(

**Comment by navalchand** [comment]
Here’s what I've accomplished so far https://github.com/langchain-ai/open-canvas/pull/144. Please review and let me know if it's ready/can be merge.

By the way, I’m not very experienced with Java and TypeScript, but with some help from the new Claude, I managed to get it working.
